version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: vv-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/vv1.conf:/etc/nginx/conf.d/vv1.conf
      - ./nginx/vv2.conf:/etc/nginx/conf.d/vv2.conf
    depends_on:
      - front1
      - front2
    networks:
      - vv-network

networks:
  vv-network:
    driver: bridge
