version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: vv-nginx
    ports:
      - "80:80"
    volumes:
      - ./vv1.conf:/etc/nginx/conf.d/vv1.conf
      - ./vv2.conf:/etc/nginx/conf.d/vv2.conf
      - ./vv11.conf:/etc/nginx/conf.d/vv11.conf
    restart: unless-stopped
    networks:
      - dock-vv-network

networks:
  dock-vv-network:
    external: true
